apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---            
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-failuremanager
spec:
  selector:
    matchLabels:
      app: mongo-failuremanager
  template:
    metadata:
      labels:
        app: mongo-failuremanager
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---            
apiVersion: v1
kind: Service
metadata:
  name: mongo-failuremanager
spec:
  selector:
    app: mongo-failuremanager
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer
