apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpufailureprobe
spec:
  selector:
    matchLabels:
      app: cpufailureprobe
  template:
    metadata:
      labels:
        app: cpufailureprobe
    spec:
      serviceAccountName: kubow-user
      containers:
      - name: cpufailureprobe
        image: californibrs/cpufailureprobe
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cpufailureprobe
spec:
  type: LoadBalancer
  selector:
    app: cpufailureprobe
  ports:
  - port: 5020 # port from application
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpufailuregauge
spec:
  selector:
    matchLabels:
      app: cpufailuregauge
  template:
    metadata:
      labels:
        app: cpufailuregauge
    spec:
      serviceAccountName: kubow-user
      containers:
      - name: cpufailuregauge
        image: californibrs/cpufailuregauge
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cpufailuregauge
spec:
  type: LoadBalancer
  selector:
    app: cpufailuregauge
  ports:
  - port: 5030 # port from application

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentinfoscalabilityaprobe
spec:
  selector:
    matchLabels:
      app: deploymentinfoscalabilityaprobe
  template:
    metadata:
      labels:
        app: deploymentinfoscalabilityaprobe
    spec:
      serviceAccountName: kubow-user
      containers:
      - name: deploymentinfoscalabilityaprobe
        image: californibrs/deploymentinfoscalabilityaprobe
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: deploymentinfoscalabilityaprobe
spec:
  type: LoadBalancer
  selector:
    app: deploymentinfoscalabilityaprobe
  ports:
  - port: 5040 # port from application
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentinfoscalabilityagauge
spec:
  selector:
    matchLabels:
      app: deploymentinfoscalabilityagauge
  template:
    metadata:
      labels:
        app: deploymentinfoscalabilityagauge
    spec:
      serviceAccountName: kubow-user
      containers:
      - name: deploymentinfoscalabilityagauge
        image: californibrs/deploymentinfoscalabilityagauge
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: deploymentinfoscalabilityagauge
spec:
  type: LoadBalancer
  selector:
    app: deploymentinfoscalabilityagauge
  ports:
  - port: 5050 # port from application
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentinfofidelityaprobe
spec:
  selector:
    matchLabels:
      app: deploymentinfofidelityaprobe
  template:
    metadata:
      labels:
        app: deploymentinfofidelityaprobe
    spec:
      serviceAccountName: kubow-user
      containers:
      - name: deploymentinfofidelityaprobe
        image: californibrs/deploymentinfofidelityaprobe
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: deploymentinfofidelityaprobe
spec:
  type: LoadBalancer
  selector:
    app: deploymentinfofidelityaprobe
  ports:
  - port: 5041 # port from application


---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentinfofidelityagauge
spec:
  selector:
    matchLabels:
      app: deploymentinfofidelityagauge
  template:
    metadata:
      labels:
        app: deploymentinfofidelityagauge
    spec:
      serviceAccountName: kubow-user
      containers:
      - name: deploymentinfofidelityagauge
        image: californibrs/deploymentinfofidelityagauge
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: deploymentinfofidelityagauge
spec:
  type: LoadBalancer
  selector:
    app: deploymentinfofidelityagauge
  ports:
  - port: 5051 # port from application
---



apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gauges-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "nginx-ingress.gauges.svc"
    http:
      paths:

      #Endpoints
      - path: /getcpufailuregauge
        backend:
          serviceName: cpufailuregauge
          servicePort: 5030
      - path: /setcpufailuregauge
        backend:
          serviceName: cpufailuregauge
          servicePort: 5030         

      - path: /getdeploymentinfoscalabilityagauge    
        backend:
          serviceName: deploymentinfoscalabilityagauge
          servicePort: 5050
      - path: /setdeploymentinfoscalabilityagauge
        backend:
          serviceName: deploymentinfoscalabilityagauge
          servicePort: 5050             


      - path: /getdeploymentinfofidelityagauge    
        backend:
          serviceName: deploymentinfofidelityagauge
          servicePort: 5051
      - path: /setdeploymentinfofidelityagauge
        backend:
          serviceName: deploymentinfofidelityagauge
          servicePort: 5051             

